artifacts:
  stackoverflow-dataset:
    path: data/data.xml
    type: dataset
    desc: Initial XML StackOverflow dataset (raw data)
  text-classification:
    path: model.pkl
    desc: Detect whether the given stackoverflow question should have R language tag
    type: model
    labels:
    - nlp
    - classification
    - stackoverflow
plots:
- ROC:
    template: simple
    x: fpr
    y:
      eval/live/plots/sklearn/roc/train.json: tpr
      eval/live/plots/sklearn/roc/test.json: tpr
- Confusion-Matrix:
    template: confusion
    x: actual
    y:
      eval/live/plots/sklearn/cm/train.json: predicted
      eval/live/plots/sklearn/cm/test.json: predicted
- Precision-Recall:
    template: simple
    x: recall
    y:
      eval/prc/train.json: precision
      eval/prc/test.json: precision
- eval/importance.png
stages:
  Prepare:
    cmd: zntrack run src.prepare.Prepare --name Prepare
    deps:
    - data/data.xml
    params:
    - Prepare
    outs:
    - data/prepared
    - nodes/Prepare/uuid
  Featurize:
    cmd: zntrack run src.featurization.Featurize --name Featurize
    deps:
    - data/prepared
    params:
    - Featurize
    outs:
    - data/features
    - nodes/Featurize/uuid
  Train:
    cmd: zntrack run src.train.Train --name Train
    deps:
    - data/features
    params:
    - Train
    outs:
    - model.pkl
    - nodes/Train/uuid
  Evaluate:
    cmd: zntrack run src.evaluate.Evaluate --name Evaluate
    deps:
    - data/features
    - model.pkl
    outs:
    - eval/importance.png
    - eval/live/metrics.json:
        cache: false
    - eval/live/plots:
        cache: false
    - eval/prc:
        cache: false
    - nodes/Evaluate/uuid
